### ISSUE TITLE
Security: DOS Attack on Unexpected Inputs

### ISSUE THREAD

**Issue by henfredemars** [c1moore/frankRS#12]
A denial of service attack exists in our controllers relating to malformed requests. We should catch any exceptions thrown in the controller and report an error instead of allowing the entire app to crash. 

Please catch exceptions thrown in the controllers.

**Comment by c1moore** [comment]
This may not be the best solution.  Simply catching all uncaught exceptions can leave data in an unclean/undefined state.  Restarting the server after uncaught exceptions may be avoidable, but forever.js handles this gracefully and I can use Node Clusters to run multiple processes if one process fails.  There is also something called domains in Node.  I am researching their use and how to implement them now.

For further reading, visit:
 - http://shapeshed.com/uncaught-exceptions-in-node/ (Explains why domains may be the best solution and why other solutions fall short)
 - http://stackoverflow.com/questions/5999373/how-do-i-prevent-node-js-from-crashing-try-catch-doesnt-work
 - http://stackoverflow.com/questions/8114977/recover-from-uncaught-exception-in-node-js (The comments on the selected answer are insightful on why the server should be restarted)

**Comment by c1moore** [comment]
This issue is closed as of commit 7e6614271fea9533bfc4efbe3d58c5cffa5502bd.

Clusters creates several child processes when starting the site.  If an fatal error occurs, Domains catches them, makes the child process stop listening for new request, returns a 500 error to the user, and kills the child process (in that order).  Meanwhile another process begins taking requests.  Once the child process is killed, another one takes its place.

I will begin removing all try-catches that were previously added for the sole purpose of keeping the server from crashing.
